spring.datasource.url=jdbc:postgresql://erp_db_tmrn_user:TYA8ykg02tCOfFmvZiI3twp5CeVuLMfY@dpg-d6t887chg0os73fkvq40-a.oregon-postgres.render.com:5432/erp_db_tmrn
spring.datasource.username=erp_db_tmrn_user
spring.datasource.password=TYA8ykg02tCOfFmvZiI3twp5CeVuLMfY
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true